version: "3.9"

volumes:
  redisdata:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
